//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : uwt
	/// Data Source    : 47.92.200.192
	/// Server Version : 5.7.17-log
	/// </summary>
	public partial class UwtDB : LinqToDB.Data.DataConnection
	{
		public ITable<UwtHelper>             UwtHelpers             { get { return this.GetTable<UwtHelper>(); } }
		public ITable<UwtNormalsBanner>      UwtNormalsBanners      { get { return this.GetTable<UwtNormalsBanner>(); } }
		public ITable<UwtNormalsFile>        UwtNormalsFiles        { get { return this.GetTable<UwtNormalsFile>(); } }
		public ITable<UwtNormalsNews>        UwtNormalsNews         { get { return this.GetTable<UwtNormalsNews>(); } }
		public ITable<UwtNormalsNewsCate>    UwtNormalsNewsCates    { get { return this.GetTable<UwtNormalsNewsCate>(); } }
		public ITable<UwtNormalsVersion>     UwtNormalsVersions     { get { return this.GetTable<UwtNormalsVersion>(); } }
		public ITable<UwtUsersAccount>       UwtUsersAccounts       { get { return this.GetTable<UwtUsersAccount>(); } }
		public ITable<UwtUsersLoginHis>      UwtUsersLoginHis       { get { return this.GetTable<UwtUsersLoginHis>(); } }
		public ITable<UwtUsersMenuGroup>     UwtUsersMenuGroups     { get { return this.GetTable<UwtUsersMenuGroup>(); } }
		public ITable<UwtUsersMenuGroupItem> UwtUsersMenuGroupItems { get { return this.GetTable<UwtUsersMenuGroupItem>(); } }
		public ITable<UwtUsersModule>        UwtUsersModules        { get { return this.GetTable<UwtUsersModule>(); } }
		public ITable<UwtUsersRole>          UwtUsersRoles          { get { return this.GetTable<UwtUsersRole>(); } }
		public ITable<UwtUsersRoleModuleRef> UwtUsersRoleModuleRefs { get { return this.GetTable<UwtUsersRoleModuleRef>(); } }
		public ITable<UwtWechatsUser>        UwtWechatsUsers        { get { return this.GetTable<UwtWechatsUser>(); } }

		public UwtDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public UwtDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("uwt_helpers")]
	public partial class UwtHelper
	{
		[Column("id"),           PrimaryKey,  Identity] public int       Id          { get; set; } // int(11)
		[Column("title"),        NotNull              ] public string    Title       { get; set; } // varchar(255)
		[Column("content"),         Nullable          ] public string    Content     { get; set; } // text
		[Column("summary"),      NotNull              ] public string    Summary     { get; set; } // varchar(255)
		[Column("publish_time"),    Nullable          ] public DateTime? PublishTime { get; set; } // datetime
		[Column("url"),          NotNull              ] public string    Url         { get; set; } // text
		/// <summary>
		/// 作者名称（随便写的东西）
		/// </summary>
		[Column("author"),       NotNull              ] public string    Author      { get; set; } // varchar(255)
		/// <summary>
		/// 编辑者Id
		/// </summary>
		[Column("modify_id"),    NotNull              ] public int       ModifyId    { get; set; } // int(11)
		/// <summary>
		/// 创建者Id
		/// </summary>
		[Column("creator_id"),   NotNull              ] public int       CreatorId   { get; set; } // int(11)
		[Column("add_time"),     NotNull              ] public DateTime  AddTime     { get; set; } // datetime
		[Column("update_time"),  NotNull              ] public DateTime  UpdateTime  { get; set; } // datetime
		[Column("valid"),        NotNull              ] public bool      Valid       { get; set; } // tinyint(1)
	}

	[Table("uwt_normals_banners")]
	public partial class UwtNormalsBanner
	{
		[Column("id"),          PrimaryKey,  Identity] public int      Id         { get; set; } // int(11)
		[Column("target"),         Nullable          ] public string   Target     { get; set; } // varchar(255)
		[Column("target_type"), NotNull              ] public string   TargetType { get; set; } // enum('Mini','Web','Page','None')
		[Column("image"),       NotNull              ] public string   Image      { get; set; } // varchar(255)
		[Column("cate"),        NotNull              ] public string   Cate       { get; set; } // enum('Banner','Environment','Course')
		[Column("title"),          Nullable          ] public string   Title      { get; set; } // varchar(15)
		[Column("sub_title"),      Nullable          ] public string   SubTitle   { get; set; } // varchar(15)
		[Column("desc"),           Nullable          ] public string   Desc       { get; set; } // varchar(255)
		[Column("index"),       NotNull              ] public int      Index      { get; set; } // int(11)
		[Column("add_time"),    NotNull              ] public DateTime AddTime    { get; set; } // timestamp
		[Column("update_time"), NotNull              ] public DateTime UpdateTime { get; set; } // timestamp
		[Column("valid"),       NotNull              ] public bool     Valid      { get; set; } // tinyint(1)
	}

	[Table("uwt_normals_files")]
	public partial class UwtNormalsFile
	{
		[Column("id"),             PrimaryKey,  Identity] public int      Id           { get; set; } // int(11)
		[Column("filename"),       NotNull              ] public string   Filename     { get; set; } // varchar(255)
		[Column("desc"),              Nullable          ] public string   Desc         { get; set; } // varchar(255)
		[Column("path"),              Nullable          ] public string   Path         { get; set; } // varchar(255)
		[Column("file_size"),      NotNull              ] public long     FileSize     { get; set; } // bigint(20)
		[Column("type"),           NotNull              ] public string   Type         { get; set; } // varchar(63)
		[Column("add_account_id"), NotNull              ] public int      AddAccountId { get; set; } // int(11)
		[Column("add_time"),       NotNull              ] public DateTime AddTime      { get; set; } // timestamp
	}

	[Table("uwt_normals_news")]
	public partial class UwtNormalsNews
	{
		[Column("id"),          PrimaryKey,  Identity] public int      Id         { get; set; } // int(11)
		[Column("title"),       NotNull              ] public string   Title      { get; set; } // varchar(255)
		[Column("summary"),     NotNull              ] public string   Summary    { get; set; } // varchar(255)
		[Column("content"),        Nullable          ] public string   Content    { get; set; } // longtext
		[Column("add_time"),    NotNull              ] public DateTime AddTime    { get; set; } // timestamp
		[Column("update_time"), NotNull              ] public DateTime UpdateTime { get; set; } // timestamp
		[Column("valid"),       NotNull              ] public bool     Valid      { get; set; } // tinyint(1)
	}

	[Table("uwt_normals_news_cates")]
	public partial class UwtNormalsNewsCate
	{
		[Column("id"),          PrimaryKey,  Identity] public int      Id         { get; set; } // int(11)
		[Column("title"),       NotNull              ] public string   Title      { get; set; } // varchar(255)
		[Column("sub_title"),      Nullable          ] public string   SubTitle   { get; set; } // varchar(255)
		[Column("desc"),           Nullable          ] public string   Desc       { get; set; } // varchar(255)
		[Column("p_id"),        NotNull              ] public int      PId        { get; set; } // int(11)
		[Column("large_icon"),  NotNull              ] public string   LargeIcon  { get; set; } // varchar(255)
		[Column("icon"),        NotNull              ] public string   Icon       { get; set; } // varchar(255)
		[Column("mini_icon"),   NotNull              ] public string   MiniIcon   { get; set; } // varchar(255)
		[Column("valid"),       NotNull              ] public bool     Valid      { get; set; } // tinyint(1)
		[Column("add_time"),    NotNull              ] public DateTime AddTime    { get; set; } // timestamp
		[Column("update_time"), NotNull              ] public DateTime UpdateTime { get; set; } // timestamp
	}

	[Table("uwt_normals_versions")]
	public partial class UwtNormalsVersion
	{
		[Column("id"),           PrimaryKey, Identity] public int      Id          { get; set; } // int(11)
		/// <summary>
		/// 版本名称
		/// </summary>
		[Column("name"),         NotNull             ] public string   Name        { get; set; } // varchar(255)
		/// <summary>
		/// 版本号 显示用
		/// </summary>
		[Column("version"),      NotNull             ] public string   Version     { get; set; } // varchar(255)
		/// <summary>
		/// 日志
		/// </summary>
		[Column("logs"),         NotNull             ] public string   Logs        { get; set; } // text
		/// <summary>
		/// 数值版本号，用于排序，越大版本越新
		/// </summary>
		[Column("version_no"),   NotNull             ] public int      VersionNo   { get; set; } // int(11)
		/// <summary>
		/// 下载地址
		/// </summary>
		[Column("path"),         NotNull             ] public string   Path        { get; set; } // varchar(255)
		/// <summary>
		/// 类型
		/// </summary>
		[Column("type"),         NotNull             ] public string   Type        { get; set; } // varchar(255)
		/// <summary>
		/// 发布时间
		/// </summary>
		[Column("publish_time"), NotNull             ] public DateTime PublishTime { get; set; } // datetime
		/// <summary>
		/// 编译时间
		/// </summary>
		[Column("build_time"),   NotNull             ] public DateTime BuildTime   { get; set; } // datetime
		/// <summary>
		/// 添加时间
		/// </summary>
		[Column("add_time"),     NotNull             ] public DateTime AddTime     { get; set; } // datetime
		/// <summary>
		/// 有效性
		/// </summary>
		[Column("valid"),        NotNull             ] public bool     Valid       { get; set; } // tinyint(1)
	}

	[Table("uwt_users_accounts")]
	public partial class UwtUsersAccount
	{
		[Column("id"),              PrimaryKey,  Identity] public int       Id            { get; set; } // int(11)
		[Column("account"),            Nullable          ] public string    Account       { get; set; } // varchar(64)
		[Column("password"),           Nullable          ] public string    Password      { get; set; } // varchar(40)
		[Column("role_id"),         NotNull              ] public int       RoleId        { get; set; } // int(11)
		[Column("status"),          NotNull              ] public string    Status        { get; set; } // enum('enabled','disabled','writenoff')
		[Column("last_login_time"),    Nullable          ] public DateTime? LastLoginTime { get; set; } // datetime
		[Column("add_time"),        NotNull              ] public DateTime  AddTime       { get; set; } // timestamp
	}

	[Table("uwt_users_login_his")]
	public partial class UwtUsersLoginHis
	{
		[Column("id"),       PrimaryKey, Identity] public int      Id       { get; set; } // int(11)
		/// <summary>
		/// 填写的用户名
		/// </summary>
		[Column("username"), NotNull             ] public string   Username { get; set; } // varchar(255)
		/// <summary>
		/// 填写的密码
		/// </summary>
		[Column("pwd"),      NotNull             ] public string   Pwd      { get; set; } // varchar(255)
		/// <summary>
		/// 可能的用户为0是登录时用户名不对
		/// </summary>
		[Column("a_id"),     NotNull             ] public int      AId      { get; set; } // int(11)
		/// <summary>
		/// 0为失败 1为成功
		/// </summary>
		[Column("status"),   NotNull             ] public bool     Status   { get; set; } // tinyint(1)
		/// <summary>
		/// 操作时间
		/// </summary>
		[Column("add_time"), NotNull             ] public DateTime AddTime  { get; set; } // timestamp
	}

	[Table("uwt_users_menu_groups")]
	public partial class UwtUsersMenuGroup
	{
		[Column("id"),         PrimaryKey,  Identity] public int      Id        { get; set; } // int(11)
		[Column("name"),       NotNull              ] public string   Name      { get; set; } // varchar(255)
		[Column("desc"),          Nullable          ] public string   Desc      { get; set; } // varchar(255)
		[Column("page_count"), NotNull              ] public int      PageCount { get; set; } // int(11)
		[Column("auth_count"), NotNull              ] public int      AuthCount { get; set; } // int(11)
		[Column("add_time"),   NotNull              ] public DateTime AddTime   { get; set; } // timestamp
		[Column("valid"),      NotNull              ] public bool     Valid     { get; set; } // tinyint(1)
	}

	[Table("uwt_users_menu_group_items")]
	public partial class UwtUsersMenuGroupItem
	{
		[Column("id"),          PrimaryKey,  Identity] public int      Id         { get; set; } // int(11)
		[Column("title"),       NotNull              ] public string   Title      { get; set; } // varchar(255)
		/// <summary>
		/// 图标
		/// </summary>
		[Column("icon"),        NotNull              ] public string   Icon       { get; set; } // varchar(255)
		/// <summary>
		/// 显示提示
		/// </summary>
		[Column("tooltip"),     NotNull              ] public string   Tooltip    { get; set; } // varchar(255)
		/// <summary>
		/// 说明
		/// </summary>
		[Column("desc"),           Nullable          ] public string   Desc       { get; set; } // varchar(255)
		[Column("pid"),         NotNull              ] public int      Pid        { get; set; } // int(11)
		[Column("group_id"),    NotNull              ] public int      GroupId    { get; set; } // int(11)
		/// <summary>
		/// Module的ID
		/// </summary>
		[Column("url"),         NotNull              ] public int      Url        { get; set; } // int(11)
		[Column("index"),       NotNull              ] public int      Index      { get; set; } // int(11)
		[Column("add_time"),    NotNull              ] public DateTime AddTime    { get; set; } // timestamp
		[Column("update_time"), NotNull              ] public DateTime UpdateTime { get; set; } // timestamp
		[Column("valid"),       NotNull              ] public bool     Valid      { get; set; } // tinyint(1)
	}

	[Table("uwt_users_modules")]
	public partial class UwtUsersModule
	{
		[Column("id"),   PrimaryKey, Identity] public int    Id   { get; set; } // int(11)
		[Column("name"), NotNull             ] public string Name { get; set; } // varchar(64)
		[Column("url"),  NotNull             ] public string Url  { get; set; } // varchar(255)
		[Column("type"), NotNull             ] public string Type { get; set; } // enum('page','api')
	}

	[Table("uwt_users_roles")]
	public partial class UwtUsersRole
	{
		[Column("id"),            PrimaryKey,  Identity] public int      Id          { get; set; } // int(11)
		/// <summary>
		/// 角色名
		/// </summary>
		[Column("name"),          NotNull              ] public string   Name        { get; set; } // varchar(255)
		/// <summary>
		/// 角色主页地址
		/// </summary>
		[Column("home_page_url"), NotNull              ] public string   HomePageUrl { get; set; } // varchar(255)
		[Column("desc"),             Nullable          ] public string   Desc        { get; set; } // varchar(255)
		[Column("menu_group_id"), NotNull              ] public int      MenuGroupId { get; set; } // int(11)
		[Column("add_time"),      NotNull              ] public DateTime AddTime     { get; set; } // timestamp
		[Column("valid"),         NotNull              ] public bool     Valid       { get; set; } // tinyint(1)
	}

	[Table("uwt_users_role_module_ref")]
	public partial class UwtUsersRoleModuleRef
	{
		[Column("id"),   PrimaryKey, Identity] public int Id  { get; set; } // int(11)
		[Column("r_id"), NotNull             ] public int RId { get; set; } // int(11)
		[Column("m_id"), NotNull             ] public int MId { get; set; } // int(11)
	}

	[Table("uwt_wechats_users")]
	public partial class UwtWechatsUser
	{
		[Column("id"),         PrimaryKey, Identity] public int      Id        { get; set; } // int(11)
		[Column("nick_name"),  NotNull             ] public string   NickName  { get; set; } // varchar(255)
		[Column("token"),      NotNull             ] public string   Token     { get; set; } // varchar(32)
		[Column("open_id"),    NotNull             ] public string   OpenId    { get; set; } // varchar(64)
		[Column("gender"),     NotNull             ] public sbyte    Gender    { get; set; } // tinyint(4)
		[Column("language"),   NotNull             ] public string   Language  { get; set; } // varchar(16)
		[Column("country"),    NotNull             ] public string   Country   { get; set; } // varchar(32)
		[Column("city"),       NotNull             ] public string   City      { get; set; } // varchar(32)
		[Column("province"),   NotNull             ] public string   Province  { get; set; } // varchar(32)
		[Column("avatar_url"), NotNull             ] public string   AvatarUrl { get; set; } // varchar(255)
		[Column("add_time"),   NotNull             ] public DateTime AddTime   { get; set; } // datetime
	}

	public static partial class TableExtensions
	{
		public static UwtHelper Find(this ITable<UwtHelper> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtNormalsBanner Find(this ITable<UwtNormalsBanner> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtNormalsFile Find(this ITable<UwtNormalsFile> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtNormalsNews Find(this ITable<UwtNormalsNews> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtNormalsNewsCate Find(this ITable<UwtNormalsNewsCate> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtNormalsVersion Find(this ITable<UwtNormalsVersion> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtUsersAccount Find(this ITable<UwtUsersAccount> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtUsersLoginHis Find(this ITable<UwtUsersLoginHis> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtUsersMenuGroup Find(this ITable<UwtUsersMenuGroup> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtUsersMenuGroupItem Find(this ITable<UwtUsersMenuGroupItem> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtUsersModule Find(this ITable<UwtUsersModule> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtUsersRole Find(this ITable<UwtUsersRole> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtUsersRoleModuleRef Find(this ITable<UwtUsersRoleModuleRef> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UwtWechatsUser Find(this ITable<UwtWechatsUser> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
